### ISSUE TITLE
Statistical analysis: point #1

### ISSUE THREAD

**Issue by tobiasz135** [IIS-ZPI/ZPI2022_IO2_Coin_Masters#17]
```
Wyznaczenie ilości sesji wzrostowych, spadkowych i 
bez zmian w okresach ostatniego 1 tygodnia, 2 tygodni, 
1 miesiąca, 1 kwartału, pół roku oraz 1 roku dla wybranej przez użytkownika waluty
``` 
Technicznie:
- Pole wyboru (najlepiej z użyciem ParametersForm)
- Tabelka wynikowa

**Comment by tobiasz135** [comment]
gitkraken://repolink/9ebf6fab736c0865a756745c72417594af5b394b/commit/53447e3c0615af14e22891a3a8afdf9ec2fa7baa?url=https%3A%2F%2Fgithub.com%2FIIS-ZPI%2FZPI2022_IO2_Coin_Masters.git

**Comment by mario0000o7** [comment]
[#e27c661](https://github.com/IIS-ZPI/ZPI2022_IO2_Coin_Masters/commit/e27c66104c27c64a81a646030a338b630a7a86f2)

**Comment by tobiasz135** [comment]
[#53447e3](https://github.com/IIS-ZPI/ZPI2022_IO2_Coin_Masters/commit/53447e3c0615af14e22891a3a8afdf9ec2fa7baa)
