### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by tobiasz135** [IIS-ZPI/ZPI2022_IO2_Coin_Masters#25]
Create tests which will check the results of the calculation functions and visibility of elements.
Everyone has to create tests to their own functionallities. If you haven't created any additional functions, create only visibility tests.

**Comment by mario0000o7** [comment]
[#c45c8c1](https://github.com/IIS-ZPI/ZPI2022_IO2_Coin_Masters/commit/c45c8c1a8ce829c7add6ed6e6439a9d5003efbd2)

**Comment by mario0000o7** [comment]
[#2b53275](https://github.com/IIS-ZPI/ZPI2022_IO2_Coin_Masters/commit/2b5327560e65ae5369cffeeb45fe2861324b1d61)
