### ISSUE TITLE
Fix CI/CD - Code refactor

### ISSUE THREAD

**Issue by tobiasz135** [IIS-ZPI/ZPI2022_IO2_Coin_Masters#26]
Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.

Failed to compile.

Check Esling errors.

**Comment by mario0000o7** [comment]
[#56acb6a](https://github.com/IIS-ZPI/ZPI2022_IO2_Coin_Masters/commit/56acb6a937f7d06cdfb700c5fd2df9897dc721b9)
